### PR TITLE
EM - Limit stryker and other frontend testing to frontend directory; limit backend testing to src and related files

### LINKED ISSUE #14: Create component to list sections for a Personal Schedule
# Overview
In this issue, you will create a new component ```PersonalSchedulesTable``` that takes a list of PersonalSection objects, one that corresponds to the output returned by the ```/api/personalSections/all endpoint```.

It should display at least the following columns:

- courseId (e.g. "CMPSC 156")
- enrollCd (e.g. "58891")
- section (e.g. "0100")
- title
- Enrolled (similar to the way it is displayed in ```SectionsTable``` , e.g. ```105/110```, using the ```convertToFraction``` utility, like like this code from ```SectionsTable.js```
         ```accessor: (row) => convertToFraction(row.section.enrolledTotal, row.section.maxEnroll),```
- Location
- Days
- Time
- Instructor
Note: it possible that you might be able to use the ```SectionsTable``` component directly, if the backend can be adjusted so that the JSON has the same "shape" as that consumed by the ```SectionsTable``` component.

If you take that approach, you might be able to replace this issue into, instead, aligning the output of the ```/api/personalSections/all``` to be the same as the output for ```/api/sections/basicsearch``` If that's the approach you take, create a separate issue describing that.

# Details

If you go to the Personal Schedules / List menu, you see this page:

If you then click on "Details" for any particular schedule, you see a page like this:

Look at that place that says: "This is where the courses will go". In this issue, we are going to create the component that will go there.

Note that this issue does NOT include adding that component into the ```PersonalSchedulesDetailPage```. That is a separate issue, in which we replace the words in this code from ```PersonalSchedulesDetailsPage``` with a reference to this new component, but also we have to work with hooking up the page to the backend... all of that will require a lot of testing, so let's defer that to another issue.

```return (
    <BasicLayout>
      <div className="pt-2">
        <h1>PersonalSchedules Details</h1>
        {personalSchedule &&
                <PersonalSchedulesTable personalSchedules={[personalSchedule]} showButtons={false} />
            }
            <p>
                This is where the list of courses will go 
            </p>
      </div>
    </BasicLayout>
  )```
That is, in a FUTURE issue, the part that says: ```

This is where the list of courses will go```

eventually gets replaced with ` or something like that, but in THIS issue, we are only creating the `PersonalSectionsTable` component.

### PR DESCRIPTION
**Pull request by CircusPigeon**
Closes #14 by adding a path condition for frontend github tests 30, 32, 34, and 36, and backend github tests 10, 12, and 14 so that they are only run when files in the relevant paths are modified.

### CODE REVIEW

**Review by dantle1 — APPROVED** [review]
LGTM

**Comment by crdgdr** [comment]
This is linking to the wrong issue. Could someone with the correct permissions change that?

**Review by pconrad — CHANGES_REQUESTED** [review]
The .DS_Store file should not be part of this ... also I wonder if some other PR got there first?

There doesn't seem to be anything here left to merge?

**Comment by pconrad** [comment]
I think this PR is now moot... the changes were already in the 6pm code base from a staff PR.

**Pull request closed without merging**
